// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWX2pyOwuY_fXOkUUYoYEqMWw00AslPQo',
    appId: '1:317008220879:android:15c1fab52adaadec2eddba',
    messagingSenderId: '317008220879',
    projectId: 'smart-printer-9f46e',
    storageBucket: 'smart-printer-9f46e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCeW2G1w6O2GwSgIxboz2ztVxzAirQ4tA',
    appId: '1:317008220879:ios:10c172d9e7360ba02eddba',
    messagingSenderId: '317008220879',
    projectId: 'smart-printer-9f46e',
    storageBucket: 'smart-printer-9f46e.firebasestorage.app',
    iosBundleId: 'smartprinter.mobileprint.wirelessprinter.printdocuments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCeW2G1w6O2GwSgIxboz2ztVxzAirQ4tA',
    appId: '1:317008220879:ios:b5621758d1f45a052eddba',
    messagingSenderId: '317008220879',
    projectId: 'smart-printer-9f46e',
    storageBucket: 'smart-printer-9f46e.firebasestorage.app',
    iosBundleId: 'com.example.smartScanner',
  );
}
